const language_data = [
  { language: "Afrikaans", data: " hallo" },
  { language: "Albanian", data: " Përshëndetje" },
  { language: "Amharic", data: " ሀሎ" },
  { language: "Arabic", data: " مرحبا" },
  { language: "Armenian", data: " Բարեւ" },
  { language: "Azerbaijani", data: " Salam" },
  { language: "Basque", data: " kaixo" },
  { language: "Belarusian", data: " добры дзень" },
  { language: "Bengali", data: " হ্যালো" },
  { language: "Bosnian", data: " zdravo" },
  { language: "Bulgarian", data: " Здравейте" },
  { language: "Catalan", data: " Hola" },
  { language: "Cebuano", data: " kumusta" },
  { language: "Chinese (Simplified)", data: " 你好" },
  { language: "Chinese (Traditional)", data: " 你好" },
  { language: "Corsican", data: " Bonghjornu" },
  { language: "Croatian", data: " zdravo" },
  { language: "Czech", data: " Ahoj" },
  { language: "Danish", data: " Hej" },
  { language: "Dutch", data: " Hallo" },
  { language: "English", data: " hello" },
  { language: "Esperanto", data: " saluton" },
  { language: "Estonian", data: " Tere" },
  { language: "Finnish", data: " Hei" },
  { language: "French", data: " Bonjour" },
  { language: "Frisian", data: " Hoi" },
  { language: "Galician", data: " ola" },
  { language: "Georgian", data: " გამარჯობა" },
  { language: "German", data: " Hallo" },
  { language: "Greek", data: " Χαίρετε" },
  { language: "Gujarati", data: " નમસ્તે" },
  { language: "Haitian Creole", data: " bonjou" },
  { language: "Hausa", data: " sannu" },
  { language: "Hawaiian", data: " aloha" },
  { language: "Hebrew", data: " שלום" },
  { language: "Hindi", data: " नमस्ते" },
  { language: "Hmong", data: " nyob zoo" },
  { language: "Hungarian", data: " Helló" },
  { language: "Icelandic", data: " Halló" },
  { language: "Igbo", data: " Nnọọ" },
  { language: "Indonesian", data: " Halo" },
  { language: "Irish", data: " Dia dhuit" },
  { language: "Italian", data: " Ciao" },
  { language: "Japanese", data: " こんにちは" },
  { language: "Javanese", data: " halo" },
  { language: "Kannada", data: " ಹಲೋ" },
  { language: "Kazakh", data: " Сәлеметсіз бе" },
  { language: "Khmer", data: " សួស្តី" },
  { language: "Korean", data: " 여보세요" },
  { language: "Kurdish", data: " Slav" },
  { language: "Kyrgyz", data: " салам" },
  { language: "Lao", data: " ສະບາຍດີ" },
  { language: "Latin", data: " Salve" },
  { language: "Latvian", data: " Sveiki" },
  { language: "Lithuanian", data: " Sveiki" },
  { language: "Luxembourgish", data: " Hallo" },
  { language: "Macedonian", data: " Здраво" },
  { language: "Malagasy", data: " Salama" },
  { language: "Malay", data: " hello" },
  { language: "Malayalam", data: " ഹലോ" },
  { language: "Maltese", data: " Bongu" },
  { language: "Maori", data: " tena koutou" },
  { language: "Marathi", data: " नमस्कार" },
  { language: "Mongolian", data: " Сайн уу" },
  { language: "Myanmar (Burmese)", data: " ဟယ်လို" },
  { language: "Nepali", data: " नमस्कार" },
  { language: "Norwegian", data: " Hallo" },
  { language: "Nyanja (Chichewa)", data: " Moni" },
  { language: "Pashto", data: " سلام" },
  { language: "Persian", data: " سلام" },
  { language: "Polish", data: " dzień dobry" },
  { language: "Portuguese (Portugal, Brazil)", data: " Olá" },
  { language: "Punjabi", data: " ਸਤ ਸ੍ਰੀ ਅਕਾਲ" },
  { language: "Romanian", data: " Salut" },
  { language: "Russian", data: " Здравствуйте" },
  { language: "Samoan", data: " talofa" },
  { language: "Scots Gaelic", data: " Halò" },
  { language: "Serbian", data: " Здраво" },
  { language: "Sesotho", data: " Lumela" },
  { language: "Shona", data: " mhoro" },
  { language: "Sindhi", data: " سلام" },
  { language: "Sinhala (Sinhalese)", data: " හෙලෝ" },
  { language: "Slovak", data: " Ahoj" },
  { language: "Slovenian", data: " zdravo" },
  { language: "Somali", data: " hello" },
  { language: "Spanish", data: " Hola" },
  { language: "Sundanese", data: " Halo" },
  { language: "Swahili", data: " hello" },
  { language: "Swedish", data: " Hallå" },
  { language: "Tagalog (Filipino)", data: " Kamusta" },
  { language: "Tajik", data: " Салом" },
  { language: "Tamil", data: " வணக்கம்" },
  { language: "Telugu", data: " హలో" },
  { language: "Thai", data: " สวัสดี" },
  { language: "Turkish", data: " Merhaba" },
  { language: "Ukrainian", data: " Здрастуйте" },
  { language: "Urdu", data: " ہیلو" },
  { language: "Uzbek", data: " Salom" },
  { language: "Vietnamese", data: " xin chào" },
  { language: "Welsh", data: " Helo" },
  { language: "Xhosa", data: " Mholweni" },
  { language: "Yiddish", data: " העלא" },
  { language: "Yoruba", data: " Pẹlẹ o" },
  { language: "Zulu", data: " Sawubona" },
];
export default language_data;
